#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check
  methods: ['POST']

adding:
  path: /api/adminSys/utilisateurs
  controller: App\Controller\AdminSystemController::Adduser

updateCompte:
  path: /api/adminSys/comptes/{id}
  controller: App\Controller\CompteController::UpdateCompte
addTransaction:
  path: /api/transactions
  controller: App\Controller\TransactionController::AddTransaction
addCompte:
  path: /api/adminSys/comptes
  controller: App\Controller\CompteController::AddCompte
addingAgence:
  path: /api/agences
  controller: App\Controller\AgenceController::AddAgence
deleteTransaction:
  path: /api/transactions/delete
  controller: App\Controller\TransactionController::DeleteTransaction
addDepot:
  path: /api/depots
  controller: App\Controller\DepotController::ADDdepot
deleteDepot:
    path: /api/depots/{id}
    controller: App\Controller\DepotController::Deletedepot