#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check
  methods: ['POST']

adding:
  path: /api/adminSys/utilisateurs
  controller: App\Controller\AdminSystemController::Adduser